name: accept-pr

on:
  issue_comment:
    types:
      - created

jobs:
  rebase:
    name: accept-pr
    runs-on: ubuntu-latest    
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/accept'}}
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: rebase-from-master
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.issue.number }}
          COMMENT_USER_LOGIN: ${{ github.event.comment.user.login }}
        run: |     
            echo "${GITHUB_CONTEXT}"
            env | sort
            
            echo "> get PR detail"
            gh api repos/"${OWNER}"/"${REPO}"/pulls/"${PR_NUMBER}" > pr_detail.json
            source_branch=$(jq .head.ref pr_detail.json)
            target_branch=$(jq .base.ref pr_detail.json)
            echo "source_branch=${source_branch}, target_branch=${target_branch}"
            
            echo "> check if user is allowed to merge"
            comment_user_permission=$(gh api repos/"${OWNER}"/"${REPO}"/collaborators/lepapareil/permission -q .permission)
            echo "comment_user_permission=${comment_user_permission}"
            if [ "${comment_user_permission}" != "admin" ] ; then
                comment="❌ Sorry ${COMMENT_USER_LOGIN}, you are not allowed to accept this PR because you do not have admin permission (your actual permission is [${comment_user_permission}])."
                echo "  - ${comment}"
                gh pr comment "${PR_NUMBER}" --body "${comment}"
                exit 1
            fi
            
            echo "> check if pull request is opened and ready"
            
            
            echo "> rebase branch from master"
            git rebases origin/"${target_branch}" && exit_code=0 || exit_code=1
            echo "exit_code=${exit_code}"
            
            if [ ${exit_code} -neq 0 ] ; then
                comment="❌ Rebase ${GITHUB_REPOSITORY_OWNER}/${source_branch} from ${GITHUB_REPOSITORY_OWNER}/${target_branch} fails."
                echo "  - ${comment}"
                gh pr comment "${PR_NUMBER}" --body "${comment} Please refer to ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID} logs."
                exit ${exit_code}
            fi
            
            echo "> fast-forward into master"
