name: accept-pr

on:
  issue_comment:
    types:
      - created

jobs:
  rebase:
    name: accept-pr
    runs-on: ubuntu-latest    
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/accept'}}
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: rebase-from-master
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.issue.number }}
          COMMENT_USER_LOGIN: ${{ github.event.comment.user.login }}
        run: |     
            echo "${GITHUB_CONTEXT}"
            env | sort
            
            echo "> check if user is allowed to merge"
            comment_user_permission=$(gh api repos/"${OWNER}"/"${REPO}"/collaborators/lepapareil/permission -q .permission)
            echo "comment_user_permission=${comment_user_permission}"
            if [ "${comment_user_permission}" != "adminn" ] ; then
                comment="❌ Sorry ${COMMENT_USER_LOGIN}, you are not allowed to accept this PR because you do not have admin permission (your actual permission is [${comment_user_permission}]."
                echo "  - ${comment}"
                gh pr comment "${PR_NUMBER}" --body "${comment}"
                exit 1
            fi
            
            echo "> check if pull request is opened and ready"
            
            
            echo "> rebase branch from master"
            git rebase origin/main && exit_code=0 || exit_code=1
            if [ ${exit_code} -eq 0 ] ; then
                comment="❌ Rebase from master branch fails, please analyse  logs."
                echo "  - ${comment}"
                gh issue comment $PR_URL --body "${comment}"
                exit ${exit_code}
            else
                comment="✅ Rebase from master done."
                echo "  - ${comment}"
                gh issue comment $PR_URL --body "${comment}"
            fi
            
            echo "> fast-forward into master"
