name: accept-pr

on:
  issue_comment:
    types:
      - created

jobs:
  rebase:
    name: accept-pr
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/accept'}}
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: rebase-from-master
        env:
          GIT_TRACE: true
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.issue.number }}
          COMMENT_USER_LOGIN: ${{ github.event.comment.user.login }}
        run: |
            echo "${GITHUB_CONTEXT}"
            env | sort

            echo "> get PR detail"
            gh api repos/"${OWNER}"/"${REPO}"/pulls/"${PR_NUMBER}" > pr_detail.json
            head_ref=$(jq -rc .head.ref pr_detail.json)
            base_ref=$(jq -rc .base.ref pr_detail.json)
            pr_state=$(jq -rc .state pr_detail.json)
            pr_locked=$(jq -rc .locked pr_detail.json)
            pr_draft=$(jq -rc .draft pr_detail.json)
            pr_mergeable=$(jq -rc .mergeable pr_detail.json)
            echo "pr_state=${pr_state}"
            echo "pr_locked=${pr_locked}"
            echo "pr_draft=${pr_draft}"
            echo "pr_mergeable=${pr_mergeable}"

            echo "> check if user is allowed to merge"
            comment_user_permission=$(gh api repos/"${OWNER}"/"${REPO}"/collaborators/lepapareil/permission -q .permission)
            echo "comment_user_permission=${comment_user_permission}"
            if [ "${comment_user_permission}" = "admin" ] ; then
                comment="✅ You are allowed to accept PR"
                echo "  - ${comment}"
            else
                comment="❌ Sorry ${COMMENT_USER_LOGIN}, you are not allowed to accept this PR because you do not have admin permission (your actual permission is [${comment_user_permission}])."
                echo "  - ${comment}"
                gh pr comment "${PR_NUMBER}" --body "${comment}"
                exit 1
            fi

            echo "> check if pull request is opened and ready"


            set -x
            echo "> rebase branch from master"
            git branch
            git status
            git rebase origin/"${base_ref}" && exit_code=0 || exit_code=1
            if [ ${exit_code} -eq 0 ] ; then
                comment="✅ Rebase ${GITHUB_REPOSITORY_OWNER}/${head_ref} from ${GITHUB_REPOSITORY_OWNER}/${base_ref} succeeds."
                echo "  - ${comment}"
            else
                comment="❌ Rebase ${GITHUB_REPOSITORY_OWNER}/${head_ref} from ${GITHUB_REPOSITORY_OWNER}/${base_ref} fails."
                echo "  - ${comment}"
                gh pr comment "${PR_NUMBER}" --body "${comment} Please refer to ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID} logs."
                exit ${exit_code}
            fi
            git push && exit_code=0 || exit_code=1
            if [ ${exit_code} -eq 0 ] ; then
                comment="✅ Push rebase ${GITHUB_REPOSITORY_OWNER}/${head_ref} from ${GITHUB_REPOSITORY_OWNER}/${base_ref} succeeds."
                echo "  - ${comment}"
            else
                comment="❌ Push rebase ${GITHUB_REPOSITORY_OWNER}/${head_ref} from ${GITHUB_REPOSITORY_OWNER}/${base_ref} fails."
                echo "  - ${comment}"
                gh pr comment "${PR_NUMBER}" --body "${comment} Please refer to ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID} logs."
                exit ${exit_code}
            fi

            echo "> fast-forward into master"
