name: rebase-from-master-and-fast-forward-to-master

on:
  issue_comment:
    types:
      - created

jobs:
  rebase:
    name: rebase-from-master-and-fast-forward-to-master
    runs-on: ubuntu-latest    
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/accept'}}
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: rebase-from-master
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.issue.number }}
          PR_URL: ${{ github.event.issue.html_url }}
          EVENT_ACTOR: ${{ github.event.issue.actor.name }}
        run: |
            # debug
            echo "GITHUB_TOKEN=${GITHUB_TOKEN}, OWNER=${OWNER}, REPO=${REPO}, PR_NUMBER=${PR_NUMBER}, PR_URL=${PR_URL}, EVENT_ACTOR=${EVENT_ACTOR}"
            echo -e "GITHUB_CONTEXT:\n${GITHUB_CONTEXT}\n"
            
            # check if user is allowed to merge
            event_actor_permission=$(gh api repos/"${OWNER}"/"${REPO}"/collaborators/lepapareil/permission -q .permission)
            echo "event_actor_permission=${event_actor_permission}"
            if [ "${event_actor_permission}" != "admin" ] ; then
                gh pr comment $PR_URL --body "❌ Sorry lepapareil, but you are not allowed to accept this PR."
                exit 1
            fi
            
            # check if pull request is opened and ready
            
            
            # rebase branch from master
            
            # rebase from master
            git rebase origin/main && exit_code=0 || exit_code=1
            if [ ${exit_code} -eq 0 ] ; then
                gh issue comment $PR_URL --body "❌ Rebase from master branch fails, please read action logs."
                exit ${exit_code}
            else
                gh issue comment $PR_URL --body "✅ Rebase from master done."
            fi
            
            # fast-forward into master
