name: fast-forward

on:
  issue_comment:
    types:
      - created

jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest    
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/pintolab'}}
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Message
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'pintolab succeeded! ✅✅✅ new',
            }); 
      - name: Add comment to PR
        env:
          URL: ${{ github.event.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          env | sort
          echo ########
          echo ${{ github }}
          echo ########
          curl \
            -X POST \
            "${URL}" \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            --data '{ "body": "blah blah" }'
