name: fast-forward

on:
  issue_comment:
    types:
      - created

jobs:
  comment:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/pintolab'}}
    runs-on: ubuntu-latest
    steps:
      - name: Message
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'pintolab succeeded! ✅✅ [' + ${{ github.event.comments_url }} + '][' + ${{ github.event.pull_request.comments_url }}+ ']',
            }); 
      - name: Add comment to PR
        env:
          URL: ${{ github.event.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "blah blah" }'
